name: '@tracerbench/tracerbench-compare-action'
description: 'Perform commit-to-commit performance analysis using tracerbench'
inputs:
  use-yarn:
    description: 'Whether to install dependencies using yarn'
    required: false
  use-pnpm:
    description: 'Whether to install dependencies using pnpm'
    required: false
  pkg-manager:
    description: 'package manager to use, defaults to npm unless use-yarn or use-pnpm are set which take precedence'
    required: false
  repo-token:
    description: 'Github Auth Token with permissions for reading, creating comments on PRs as well as updating comments previously created by the action'
    required: false
  control-sha:
    description: 'SHA of the control to use for the comparison. Also used to checkout the correct files before build if build-control is true.'
  experiment-sha:
    description: 'SHA of the experiment to use for the comparison. Also used to checkout the correct files before build if build-experiment is true.'
  build-control:
    description: 'Whether to run control-build-command to produce control-dist'
    required: false
  build-experiment:
    description: 'Whether to run experiment-build-command to produce experiment-dist'
    required: false
  control-build-command:
    description: 'command to execute to produce control-dist if build-control is true'
    required: false
  control-serve-command:
    description: 'ember s --path=dist-control'
  experiment-build-command:
    description: 'command to execute to produce experiment-dist if build-experiment is true'
    required: false
  experiment-serve-command:
    description: 'ember s --path=dist-experiment'
  control-dist:
    description: 'the location of the built dist for the control-sha (e.g. the output of ember build)'
    required: false
  experiment-dist:
    description: 'the location of the built dist for the experiment-sha (e.g. the output of ember build)'
    required: false
  markers:
    description: 'markers, comma separated'
    required: false
  control-url:
    description: 'the url to sample for the control'
    required: false
  experiment-url:
    description: 'the url to sample for the experiment'
    required: false
  regression-threshold:
    description: 'threshold for estimated delta to consider failed (in addition to statistically significant)'
    required: false
  fidelity:
    description: 'low, high or number of samples'
    required: false
  debug:
    description: 'Whether to run tracerbench in debug mode'
    required: false
  is-ci-env:
    description: 'Whether to run tracerbench in CI mode'
    required: false
  upload-traces:
    description: 'Whether to upload all trace data as artifacts after the run'
    required: false
  upload-results:
    description: 'Whether to upload all generated reports as artifacts after the run'
    required: false
  clean-after-analyze:
    description: 'whether to cleanup after analysis'
    required: false
  scenarios:
    description: 'json list of scenarios keyed by name with their control+experiment urls and markers'
    required: false
  sample-timeout:
    description: 'number of seconds to wait for a sample. Default value is 30s'
    required: false
  browser-args:
    description: 'additional browser args to pass to tracerbench, comma separated'
    required: false
runs:
  using: "node20"
  main: 'src/action.mjs'
branding:
  icon: 'activity'
  color: 'orange'
